// src/lib/scriptGenerator.ts

import { App } from "@/data/apps";
import { SystemTweak } from "@/data/tweaks";
import JSZip from "jszip";

const FREE_NAGWARE = `
Write-Host ""
Write-Host "  ╔════════════════════════════════════════════════════╗" -ForegroundColor Red
Write-Host "  ║       FREE VERSION — SetupScript.io                ║" -ForegroundColor Red
Write-Host "  ║   Want to remove this wait and gain FPS?           ║" -ForegroundColor Red
Write-Host "  ║       Buy GOD MODE for only $9                     ║" -ForegroundColor Red
Write-Host "  ║            setupscript.io/pricing                  ║" -ForegroundColor Red
Write-Host "  ╚════════════════════════════════════════════════════╝" -ForegroundColor Red
Write-Host ""
Write-Host "  Waiting 15 seconds..." -ForegroundColor Yellow
Start-Sleep -Seconds 15
Write-Host ""
`;

const SCRIPT_HEADER = `<#
.SYNOPSIS
    Script generated by SetupScript.io
.DESCRIPTION
    Installs applications and applies system tweaks automatically.
    Generated on: {DATE}
    This script was generated at SetupScript.io - https://setupscript.io
#>
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Start-Process powershell.exe -Verb RunAs -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File \`"$($MyInvocation.MyCommand.Path)\`""
    exit
}
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
chcp 65001 | Out-Null
$ErrorActionPreference = "Continue"
$ProgressPreference = "SilentlyContinue"
$errors = @()
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════════╗" -ForegroundColor Red
Write-Host "  ║         SetupScript.io — Automatic Setup         ║" -ForegroundColor Red
Write-Host "  ╚═══════════════════════════════════════════════════╝" -ForegroundColor Red
Write-Host "  Starting automated installation..." -ForegroundColor White
Write-Host ""
if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    Write-Host "[ERROR] winget not available. Install App Installer from Microsoft Store." -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}
Write-Host "[OK] winget detected. Proceeding..." -ForegroundColor Green
Write-Host ""
`;

const APPS_SECTION_HEADER = `
# ─────────────────────────────────────────────────────────────────
# SECTION 1: APPLICATION INSTALLATION
# ─────────────────────────────────────────────────────────────────
Write-Host "INSTALLING APPLICATIONS..." -ForegroundColor Magenta
`;

const TWEAKS_SECTION_HEADER = `
# ─────────────────────────────────────────────────────────────────
# SECTION 2: SYSTEM TWEAKS
# ─────────────────────────────────────────────────────────────────
Write-Host "APPLYING SYSTEM TWEAKS..." -ForegroundColor Red
`;

const SCRIPT_FOOTER = `
# ─────────────────────────────────────────────────────────────────
# COMPLETION
# ─────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Red
if ($errors.Count -eq 0) {
    Write-Host "  [OK] Setup completed without errors." -ForegroundColor Green
} else {
    Write-Host "  [!!] Errors in: $($errors -join ', ')" -ForegroundColor Yellow
}
Write-Host "  Generated by SetupScript.io" -ForegroundColor Magenta
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Red
Write-Host ""
Read-Host "Press Enter to close"
`;

export function generateInstallBlock(app: App): string {
  return `
Write-Host "  → Installing ${app.name}..." -ForegroundColor White
winget install --id ${app.wingetId} --silent --accept-package-agreements --accept-source-agreements
if ($LASTEXITCODE -eq 0) {
    Write-Host "  ✅ ${app.name} installed successfully." -ForegroundColor Green
} else {
    $errors += "${app.name}"
    Write-Host "  ⚠️  ${app.name} - already installed or error (code: $LASTEXITCODE)" -ForegroundColor Yellow
}`;
}

export function generateTweakBlock(tweak: SystemTweak): string {
  const safeApplyCommand = tweak.applyCommand.replace(/\\\\/g, '\\');
  const safeRevertCommand = tweak.revertCommand.replace(/\\\\/g, '\\');
  let block = "";

  if (tweak.risk === "high") {
    block += `
Write-Warning "[WARNING] This tweak is hard to revert: ${tweak.name}"
$confirm = Read-Host "Continue? (y/N)"
if ($confirm -ne 'y') { Write-Host "Skipped." -ForegroundColor Gray }
else {
`;
  }

  block += `
Write-Host "  → Applying: ${tweak.name}..." -ForegroundColor White
# REVERT WITH: ${safeRevertCommand.split("\n")[0]}
${safeApplyCommand}
Write-Host "  ✅ ${tweak.name} - applied." -ForegroundColor Green`;

  if (tweak.risk === "high") {
    block += `
}`;
  }

  if (tweak.requiresReboot) {
    block += `
Write-Host "  ⚠️  Requires reboot to take effect." -ForegroundColor Yellow`;
  }

  return block;
}

export interface GeneratorInput {
  selectedApps: App[];
  selectedTweaks: SystemTweak[];
  isProUser?: boolean;
}

// IDs allowed in free tier
const FREE_ALLOWED_TWEAKS = [
  "enable_dark_mode",
  "show_file_extensions",
  "show_hidden_files",
  "taskbar_left_windows11",
];

export function generateScript({
  selectedApps,
  selectedTweaks,
  isProUser = false,
}: GeneratorInput): string {
  if (selectedApps.length === 0 && selectedTweaks.length === 0) {
    return "# Select applications or tweaks to generate your script.";
  }

  const date = new Date().toLocaleDateString("en-US", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  let script = SCRIPT_HEADER.replace("{DATE}", date);

  // ── NAGWARE for Free Users ──
  if (!isProUser) {
    script += FREE_NAGWARE;
  }

  // Filter tweaks by tier
  let tweaksToApply = selectedTweaks;
  if (!isProUser) {
    tweaksToApply = selectedTweaks.filter((t) =>
      FREE_ALLOWED_TWEAKS.includes(t.id),
    );
  }

  // Apps Section
  if (selectedApps.length > 0) {
    script += APPS_SECTION_HEADER;

    const byCategory = selectedApps.reduce(
      (acc, app) => {
        if (!acc[app.category]) acc[app.category] = [];
        acc[app.category].push(app);
        return acc;
      },
      {} as Record<string, App[]>,
    );

    for (const [category, apps] of Object.entries(byCategory)) {
      script += `\n# ${category.toUpperCase().replace("_", " ")}\n`;
      for (const app of apps) {
        script += generateInstallBlock(app);
      }
    }
  }

  // Tweaks Section
  if (tweaksToApply.length > 0) {
    script += TWEAKS_SECTION_HEADER;
    for (const tweak of tweaksToApply) {
      script += generateTweakBlock(tweak);
    }
  }

  // Show skipped tweaks if free
  if (!isProUser) {
    const skippedTweaks = selectedTweaks.filter(
      (t) => !FREE_ALLOWED_TWEAKS.includes(t.id),
    );
    if (skippedTweaks.length > 0) {
      script += `\n
# ─────────────────────────────────────────────────────────────────
# ⚠️  SKIPPED TWEAKS (Require GOD MODE)
# ─────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ⚠️  Skipped ${skippedTweaks.length} tweak(s) that require GOD MODE:" -ForegroundColor Yellow`;
      for (const t of skippedTweaks) {
        script += `\nWrite-Host "     🔒 ${t.name}" -ForegroundColor DarkGray`;
      }
      script += `\nWrite-Host "  👉 Buy GOD MODE at setupscript.io/pricing" -ForegroundColor Red\nWrite-Host ""`;
    }
  }

  script += SCRIPT_FOOTER;
  return script;
}

// Función para descargar el script como archivo .ps1
export function downloadScript(
  scriptContent: string,
  filename = "setupscript.ps1",
): void {
  const bom = new Uint8Array([0xEF, 0xBB, 0xBF]);
  const encoder = new TextEncoder();
  const encoded = encoder.encode(scriptContent);
  const withBom = new Uint8Array(bom.length + encoded.length);
  withBom.set(bom, 0);
  withBom.set(encoded, bom.length);

  const blob = new Blob([withBom], { type: "application/octet-stream" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Función para copiar al portapapeles
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

// Retorno exacto del contenido batch solicitado
// Retorno exacto del contenido batch solicitado
// Retorno exacto del contenido batch solicitado
export function generateBatchLauncher(): string {
  return `@echo off
PowerShell -NoProfile -ExecutionPolicy Bypass -File "%~dp0setupscript.ps1"
pause`;
}

export async function generateAndDownloadZip(scriptContent: string): Promise<void> {
  const zip = new JSZip();

  // 1. Add setupscript.ps1 with BOM
  const bom = new Uint8Array([0xEF, 0xBB, 0xBF]);
  const encoder = new TextEncoder();
  const encoded = encoder.encode(scriptContent);
  const withBom = new Uint8Array(bom.length + encoded.length);
  withBom.set(bom, 0);
  withBom.set(encoded, bom.length);
  
  zip.file("setupscript.ps1", withBom);

  // 2. Add RUN ME.bat
  zip.file("RUN ME.bat", generateBatchLauncher());

  // 3. Add README.txt
  const readmeContent = `======================================
 SetupScript.io — HOW TO RUN
======================================

 1. Double-click "RUN ME.bat"
 2. Click "Yes" when Windows asks for admin permission
 3. Wait for the installation to complete
 4. Press Enter to close when done

======================================
 IMPORTANT
======================================

 - Do NOT move the .ps1 file to a different folder before running
 - Requires Windows 10 or Windows 11
 - Requires internet connection
 - winget must be installed (comes pre-installed on Windows 11)
   If missing: install "App Installer" from the Microsoft Store

 Generated by SetupScript.io
 https://setupscript.io
======================================`;

  zip.file("README.txt", readmeContent);

  // 4. Generate and download
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "setupscript.zip";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

